# Generated by Django 5.2.17 on 2026-09-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='consented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='flow_state',
            field=models.CharField(default='menu', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='preferred_language',
            field=models.CharField(default='en', max_length=12),
        ),
        migrations.AddField(
            model_name='participant',
            name='wa_id',
            field=models.CharField(blank=True, help_text='WhatsApp sender ID; use a restricted database in real deployments.', max_length=32, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('body', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.TextField(blank=True)),
                ('delivered', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_messages', to='care.participant')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('handled', 'Handled')], default='pending', max_length=12)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests', to='care.participant')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
