# Generated by Django 5.2.17 on 2026-10-01 07:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_participant_consented_at_participant_last_inbound_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_user_id', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='riskalert',
            options={'ordering': ['priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='recipient_counsellor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='participant',
            name='booking_choices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='participant',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='minor_assent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='outcome',
            field=models.CharField(blank=True, choices=[('concern_confirmed', 'Concern confirmed'), ('false_positive', 'False positive'), ('follow_up', 'Follow-up needed')], max_length=20),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CounsellorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepts_assignments', models.BooleanField(default=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Authorized counsellor WhatsApp number, digits with country code.', max_length=32)),
                ('notification_opt_in', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(choices=[('behaviour', 'Behaviour'), ('keyword', 'Keyword'), ('sentiment', 'Sentiment')], max_length=12)),
                ('reason', models.CharField(max_length=180)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_evidence', to='care.participant')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_slot', to='care.session')),
            ],
            options={
                'ordering': ['starts_at'],
                'constraints': [models.UniqueConstraint(fields=('counsellor', 'starts_at'), name='unique_counsellor_slot')],
            },
        ),
    ]
