# Generated by Django 5.2.17 on 2026-10-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_assignment_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundmessage',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
