# Generated by Django 5.2.17 on 2026-10-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_message_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundmessage',
            name='sentiment_risk_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='sentiment_source',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='sentiment_risk_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='sentiment_source',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
